# Generated by Django 4.2.2 on 2023-09-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
